apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-elasticsearch
  namespace: efk
  labels:
    app: elasticsearch
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi